apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret # k8s will search of this name of the file
              key: mongo-user # the file must contain the key
        
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo # this is how service and pod (above) find each other. Service foward the request to its related pods. This should match the label selector of the pod
  ports:
    - protocol: TCP
      port: 27017 # its a common practice to keep the same port, but it can be 8080 or any other.
      targetPort: 27017 # the port of the pod. The service should foward the request to